version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:5000"  # Map port 9001 on the host to port 5000 in the container
    env_file:
      - .env
    volumes:
      - ./src:/app  # Mount the src directory to /app in the container
    command: ["python", "lambda_functions.py"]